### ISSUE TITLE
Complete the `Wasting` module

### ISSUE THREAD

**Issue by tbhallett** [UCL/TLOmodel#542]
The `Wasting` module was first proposed in #289, from which `Stunting` was split out (#390), and `Wasting` was left until now.

The work to do is:
- [x] Add the ResourceFile (named here as `ResourceFile_Undernutrition.xlsx`), which was omitted in the #289
- [x] Consider the initial review comments in #289 
- [x] Introduce basic amount of refactoring and updating needed for this to function as module
- [x] Duplicate the refactoring work done for `Stunting` in #390 here.
- [x] Introduce the same level of testing as done for `Stunting` in #390.
- [x] Check that the performance of the module is as expected.

A PR has been opened that brings in the three files that will be changed (#543)

**Comment by mnjowe** [comment]
Hi Everyone

Kindly find attached outputs from the wasting module. I will not be surprised if the outputs don't entirely meet the expectation for there's still some work to be done in the code. This is just a first touch where I wanted to ensure that


1. An analysis file has been added which will give us a picture of the wasting outputs
2. All wasting tests are running(for this, I had to make some minor changes to the wasting module. see my last commits [here](https://github.com/UCL/TLOmodel/pull/543)
3. A wasting resource file has been added

May I kindly request your input on some other outputs we are expecting to see from the wasting module plus any other comment on the expectation on the current outputs. Thanks 

[wasting_outputs.docx](https://github.com/UCL/TLOmodel/files/12828032/wasting_outputs.docx)

**Comment by mnjowe** [comment]
This is noted @timcolbourn , Thanks. 

We will surely get in touch on the interpretation of parameters and the word document as soon as we are happy with  the current work on the programming side of wasting module. Thanks

**Comment by mnjowe** [comment]
Hi @timcolbourn , @tbhallett and @andrew-phillips-1(optional). Myself and @thewati have finished looking at both the code and the document. We have listed below Epi question we need some help from @timcolbourn.  For programming ones @tbhallett, They're many so we would love to work on them, push to the PR and ask for your review. Thanks

Epi issues/questions - @timcolbourn 
1.  It seems there are deaths from MAM(see [this block of code](https://github.com/UCL/TLOmodel/blob/4c089a1702260ce04a1ea2e8289966557eb681a6/src/tlo/methods/wasting.py#L646-L649)) in the module. Shouldn't deaths only occur from SAM? and all MAM cases that haven't recovered progress to SAM? 
2. The wasting poll event which occurs every month just includes *natural recovery event* which makes people recover only from moderate wasting. Shouldn't we call HSI wasting treatment events also for the treatment and recovery of those that are under SAM? As it stands there is no recovery for SAM cases. see this  class [here](https://github.com/UCL/TLOmodel/blob/4c089a1702260ce04a1ea2e8289966557eb681a6/src/tlo/methods/wasting.py#L994)

**Comment by tbhallett** [comment]
Thanks @mnjowe  and @thewati  --- very happy to do a review of the code when you're ready.

**Comment by inesll** [comment]
> Hi @timcolbourn , @tbhallett and @andrew-phillips-1(optional). Myself and @thewati have finished looking at both the code and the document. We have listed below Epi question we need some help from @timcolbourn. For programming ones @tbhallett, They're many so we would love to work on them, push to the PR and ask for your review. Thanks
> 
> Epi issues/questions - @timcolbourn
> 
> 1. It seems there are deaths from MAM(see [this block of code](https://github.com/UCL/TLOmodel/blob/4c089a1702260ce04a1ea2e8289966557eb681a6/src/tlo/methods/wasting.py#L646-L649)) in the module. Shouldn't deaths only occur from SAM? and all MAM cases that haven't recovered progress to SAM?
> 2. The wasting poll event which occurs every month just includes _natural recovery event_ which makes people recover only from moderate wasting. Shouldn't we call HSI wasting treatment events also for the treatment and recovery of those that are under SAM? As it stands there is no recovery for SAM cases. see this  class [here](https://github.com/UCL/TLOmodel/blob/4c089a1702260ce04a1ea2e8289966557eb681a6/src/tlo/methods/wasting.py#L994)

Hi @mnjowe ! Thank you for taking over the programming of wasting! 
To adress your questions: 
1. Yes that block of code is odd. Shouldn't be there, only recovery should be scheduled.
2. There is an Event scheduled for recovery of SAM to MAM - in the death poling (AcuteMalnutritionDeathPollingEvent) and in the HSIs for SAM treatment - the key event is called UpdateToMam (Event, IndividualScopeEventMixin): https://github.com/UCL/TLOmodel/blob/4c089a1702260ce04a1ea2e8289966557eb681a6/src/tlo/methods/wasting.py#L1296

I hope this helps! Happy to discuss this further.

Best, 
Ines

**Comment by inesll** [comment]
Good point! Indeed I haven't worked on the integration with the health system module. For the wasting module, there are a few symptoms registered that should prompt their care seeking based on the health seeking behaviour module's models. To add interaction with the health system in the simulation, you could call that function do_when_acute_malnutrition_assessment to occur within the generic appointments (hsi_generic_first_appts.py), for children under-5. I would suggest to add a certain probability of that function to occur (e.g. 40% for MAM, 70% for SAM - then further adjusted with calibrations), to reflect the lack of nutrition assessment at outpatient care when they seek healthcare for other conditions (health worker's performance). Unless, the appointment was initiated by the Wasting module. 

Hope this helps - happy to plan this together in a call if needed.

**Comment by mnjowe** [comment]
Great! thanks @inesll for the explanation, it is well noted. Myself and @thewati would also be happy to have a call you. what's your availability next week?

**Comment by inesll** [comment]
Sure, I am flexible, let me know the dates/times you both can do. 
Also, would be great if you could let me know what areas you would like to discuss prior to the call, so I can look through beforehand. Thanks!

**Comment by mnjowe** [comment]
Hi Ines. Once again thank you for offering us a change to have a call with you. 

We would appreciate it if we can have this call this coming **Friday 3rd November from 2-3pm Malawi time(1-2pm UK time?).**  We are interested to hear your epi thought's on the wasting events(HSI's, Deaths, Recoveries) while looking at the graphs in the undernutrition write-up(wasting section only).

May you please confirm your availability?

**Comment by inesll** [comment]
Thanks @mnjowe and @thewati for working on this and spoting some epi issues! Things to fix:

- [ ] natural recovery for MUAC and oedema when Wasting Natural Recovery events happen (I'LL DO THIS NOW)
- [ ] delete deaths from MAM at initialise population (lines 648-651) - their outcome can be determined in the next polling events
- [ ] apply a probability of nutritional status being checked at the generic appoitnments
- [ ] Update the incidence and progression rates (low priority)

**Comment by inesll** [comment]
> Thanks @mnjowe and @thewati for working on this and spoting some epi issues! Things to fix:
> 
> * [x]  natural recovery for MUAC and oedema when Wasting Natural Recovery events happen (I'LL DO THIS NOW)
> * [ ]  delete deaths from MAM at initialise population (lines 648-651) - their outcome can be determined in the next polling events
> * [ ]  apply a probability of nutritional status being checked at the generic appoitnments
> * [ ]  Update the incidence and progression rates (low priority)

@mnjowe and @thewati - actually for the first issue listed, the code already resets the values of MUAC in the WHZ>=-2 within that function muac_cutoff_by_WHZ - as it applies the probability of MUAC values again while diregarding what they had previously. I have now added the nutritional_oedema_present function which resets the probability of oedema in WHZ>=-2 regardless of their previous odema status. Therefore, there won't be no overestimates! :) 
I made this change on PR #543

**Comment by thewati** [comment]
Hi @timcolbourn , @mnjowe and I have been working on the incidence of wasting cases. Here are some results for your perusal...
Earlier, we didn't have any "not undernourished" cases in the graph
![Incidence](https://github.com/UCL/TLOmodel/assets/39279950/558e6d78-7dee-4781-aa4d-0943760686e9)

Now we have some under the "not undernourished" category and incidence cases are hovering around 0.7. Please see the image below
![new incidence](https://github.com/UCL/TLOmodel/assets/39279950/5d772521-0fce-4461-89ae-dd2801a21536)

**Comment by timcolbourn** [comment]
Thanks @thewati and @mnjowe. Please find my comments attached - it still seems like the incidence is far too high (though please also check what the graph is plotting as per my comment)
[Wasting.Plots.20_11_TC.docx](https://github.com/UCL/TLOmodel/files/13425593/Wasting.Plots.20_11_TC.docx)
, though the deaths look about right.

**Comment by timcolbourn** [comment]
Thanks @mnjowe, please find my comments and suggestions attached 
[Wasting.Plots.20_11_TC-em_TC.docx](https://github.com/UCL/TLOmodel/files/13429376/Wasting.Plots.20_11_TC-em_TC.docx)

**Comment by mnjowe** [comment]
Hi @timcolbourn and @inesll. Kindly find attached revised wasting plots. some of the changes in resource file include 

- wasting incidence at 0.02(all <4 age group)
- progress to severe wasting at 0.2(all <4 age groups) 
- deaths from SAM at 0.42.

Thanks 
[wasting_plots.docx](https://github.com/UCL/TLOmodel/files/13635767/wasting_plots.docx)

**Comment by timcolbourn** [comment]
> Hi @timcolbourn and @inesll. Kindly find attached revised wasting plots. some of the changes in resource file include
> 
> * wasting incidence at 0.02(all <4 age group)
> * progress to severe wasting at 0.2(all <4 age groups)
> * deaths from SAM at 0.42.
> 
> Thanks [wasting_plots.docx](https://github.com/UCL/TLOmodel/files/13635767/wasting_plots.docx)

Thanks @thewati and @mnjowe these new plots look good to me, well done!
